### ISSUE TITLE
Cache: add some code to check for the files being there and not overwrite if they are

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ResonantOrbitCalculator#2]
Just as a reminder:

https://forum.kerbalspaceprogram.com/index.php?/topic/177833-14x-ksp-resonant-orbit-calculator/&do=findComment&comment=3463922

**Comment by linuxgurugamer** [comment]
I do have a life, you know.  I will get to it, but it's a minor issue

**Comment by Gordon-Dry** [comment]
Of course, but having an issue on Github is better than any post in a forum thread.

**Comment by linuxgurugamer** [comment]
Fixed in next release
