### ISSUE TITLE
Suggestion: a readout that shows the length of the actual LOS? 

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ResonantOrbitCalculator#3]
Could you add a readout that shows the length of the actual LOS? 

Either inside the UI or as a tooltip when hovering over the LOS.

**Comment by linuxgurugamer** [comment]
Can't do it as a tooltip, sorry.
But, which would you prefer?  The length of the LOS, or shorted distance between two nodes (ie:  two satellites)

**Comment by Gordon-Dry** [comment]
Because the mod already calculates the positions of satellites I would say the distance between them.

But tbh I don't really understand your question; what is the difference between "the length of the LOS" and "the shorted distance between two nodes"?

**Comment by linuxgurugamer** [comment]
shortest distance between two nodes, where a node is where a satellite will be placed.

If using 3 satellites, LOS will equal the distance between two nodes, but as the number of satellites increase, the LOS will be different

**Comment by yalov** [comment]
The shortest distance between two relays in constellation on some altitude (aka distance between neighbour relays) is helpful on early career, when you are acting on the edge of CommNet range, and need to be sure, that relays in constellation will be able to reach at least neighbours (or will have 100% science transmission to the neighbours)  
it's not a rocket science, just like `2(Alt+R)×sin(π/N)`, but having the number is cozy

**Comment by Gordon-Dry** [comment]
Bumping this.
I need the distance between two relay satellites while planning a constellation to calculate the lowest needed antenna power in dBm with the RealAntenna mod.

**Comment by linuxgurugamer** [comment]
I'll see what I can do, can you suggest a short label for this?

**Comment by linuxgurugamer** [comment]
> The shortest distance between two relays in constellation on some altitude (aka distance between neighbour relays) is helpful on early career, when you are acting on the edge of CommNet range, and need to be sure, that relays in constellation will be able to reach at least neighbours (or will have 100% science transmission to the neighbours) it's not a rocket science, just like `2(Alt+R)×sin(π/N)`, but having the number is cozy

This formula, is that 2 * (altitude + planetRadius)*sin(pi/N)

where N == number of nodes?

**Comment by linuxgurugamer** [comment]
@Gordon-Dry See how this works:
https://drive.google.com/file/d/16WgF6-2GKRjhx9ihTfizCboig_jiiv6d/view?usp=sharing

**Comment by yalov** [comment]
> This formula, is that 2 * (altitude + planetRadius)*sin(pi/N)
> where N == number of nodes?

yes

**Comment by linuxgurugamer** [comment]
> > This formula, is that 2 * (altitude + planetRadius)*sin(pi/N)
> > where N == number of nodes?
> 
> yes

Thanks, I posted a beta above for you and @Gordon-Dry to try out

**Comment by Gordon-Dry** [comment]
Looks good after a quick test in VAB.
