### ISSUE TITLE
BUG + Suggestion: researching body with telescope yields 0%

### ISSUE THREAD

**Issue by DarkPR** [linuxgurugamer/ResonantOrbitCalculator#8]
BUG: I researched a body with a telescope once, it was random, I didn't get to choose which body I wanted it to research, which was annoying. It added 10% onto Moho. I did it a 2nd time, and it added 0% onto nothing, or it possibly added 10% onto a body I hadn't discovered yet. But from what I can see, nothing was added to any bodies I currently know about. I am unsure how to send my game data so you'll have to help me with that.

Suggestion: the research of a body going up only 10% per every scan (90 days minimun) you do on it? I feel like that's a bit slow. I think it should go up 33% each time, basically only having to do it 3 times to complete the research. Each time, the planet would gain a significant amount more detail compared to the previous %. 
Also, not sure if it is a bug or a feature, but please enable me to choose what body I want to research that I have unlocked, with the telescope. 

I know I can start the research with the ground telescope, and it knocks it up by 10%, but it only seems to be a 1 time thing...

**Comment by linuxgurugamer** [comment]
I think you hit the wrong mod.  This mod doesn't do any research at all, it's just an orbit calculation tool
You probably want ResearchBodies:

https://forum.kerbalspaceprogram.com/index.php?/topic/139473-18x-researchbodies-v1110-19th-oct-jun-2019/
https://github.com/JPLRepo/ResearchBodies

**Comment by DarkPR** [comment]
oh yeah, my bad haha, thanks
